version: "3"
services:
  test_db:
    container_name: test
    image: postgres:12.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"